nelmio_api_doc:
    name: PdfParser
    sandbox:
        authentication:
            delivery:             header
            # Required if http delivery is selected.
            custom_endpoint:      true
            type: basic
            name: x-wsse