services:
    _defaults:
        autowire: true
        public: true
        autoconfigure: true

    App\Controller\:
        resource: '../../Controller/*'
         tags: ['controller.service_arguments']